/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ManagePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientJPanel
     */
      private Enterprise enterprise;
    private JPanel userProcessContainer;
    
    public ManagePatientJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorJBtn = new javax.swing.JButton();
        recepientJBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        potentialMatchesJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorJBtn.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        donorJBtn.setForeground(new java.awt.Color(153, 0, 51));
        donorJBtn.setText("DONOR");
        donorJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorJBtnActionPerformed(evt);
            }
        });
        add(donorJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 56));

        recepientJBtn.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        recepientJBtn.setForeground(new java.awt.Color(0, 0, 153));
        recepientJBtn.setText("RECEPIENT");
        recepientJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepientJBtnActionPerformed(evt);
            }
        });
        add(recepientJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 120, 57));

        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, 40));

        potentialMatchesJBtn.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        potentialMatchesJBtn.setForeground(new java.awt.Color(0, 102, 0));
        potentialMatchesJBtn.setText("POTENTIAL MATCHES");
        potentialMatchesJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potentialMatchesJBtnActionPerformed(evt);
            }
        });
        add(potentialMatchesJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/donor_icon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/recepient_icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void donorJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorJBtnActionPerformed
      CreateDonorJPanel createDonorJPanel = new CreateDonorJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("createDonorJPanel", createDonorJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donorJBtnActionPerformed

    private void recepientJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepientJBtnActionPerformed
  CreateRecepientJPanel createRecepientJPanel = new CreateRecepientJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("createRecepientJPanel", createRecepientJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    }//GEN-LAST:event_recepientJBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void potentialMatchesJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potentialMatchesJBtnActionPerformed
        ViewMatchesJPanel vmjp = new ViewMatchesJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("viewPotentialMatches", vmjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_potentialMatchesJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton donorJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton potentialMatchesJBtn;
    private javax.swing.JButton recepientJBtn;
    // End of variables declaration//GEN-END:variables
}
