/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.HormonalRecords.HormonalRecords;
import Business.HormonalRecords.HormonalRecordsHistory;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.ReciepientOrganization;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ViewMatchesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMatchesJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    public ViewMatchesJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateDonorTable();
        populateRecepientTable();
        
    }
public void populateDonorTable(){
    DefaultTableModel model = (DefaultTableModel) donorListJTable.getModel();
        
        model.setRowCount(0);
        donorListJTable.setAutoCreateRowSorter(true);
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof DonorOrganization){
                for (Employee donor: org.getEmployeeDirectory().getEmployeeList()){
                    
                    double avgTemp = donor.getHormonalRecordsHistory().calculateAvgIOT();
                  donor.getHormonalRecordsHistory().setAvgTempIOT(avgTemp);
                   double avg = donor.getHormonalRecordsHistory().calculateAvgIOT();
                   System.out.println(avg);
                      Object[] row = new Object[3];
            row[0] = donor.getId();
            row[1] = donor;
            row[2] = donor.getHormonalRecordsHistory().getAvgTempIOT();
           
            model.addRow(row);
                }
            }
        }
        
        
}

public void populateRecepientTable(){
   DefaultTableModel model = (DefaultTableModel) recepientListJTable.getModel();
        
        model.setRowCount(0);
        recepientListJTable.setAutoCreateRowSorter(true);
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof ReciepientOrganization){
                for (Employee recepient: org.getEmployeeDirectory().getEmployeeList()){
                     double avgTemp = recepient.getHormonalRecordsHistory().calculateAvgIOT();
                  recepient.getHormonalRecordsHistory().setAvgTempIOT(avgTemp);
                   double avg = recepient.getHormonalRecordsHistory().calculateAvgIOT();
                   System.out.println(avg);
                      Object[] row = new Object[3];
            row[0] = recepient.getId();
            row[1] = recepient;
            row[2] = recepient.getHormonalRecordsHistory().getAvgTempIOT();
            
           
            model.addRow(row);
                }
            }
        }  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        donorListJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        recepientListJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backJBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        matchedDonorTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        matchedRecepientTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor ID", "Donor Name", "Average BBT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(donorListJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, 325, 92));

        recepientListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Recepient ID", "Recepient Name", "Average BBT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(recepientListJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 403, 325, 92));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/banner-about.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 928, -1));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 3, 36)); // NOI18N
        jLabel2.setText("Donor List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 329, 202, -1));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 3, 36)); // NOI18N
        jLabel3.setText("Recepient List");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 329, 260, -1));

        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 101, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Selected Donor:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 449, -1, 21));

        matchedDonorTxtField.setEditable(false);
        add(matchedDonorTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 488, 118, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Selected Recepient:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 452, -1, -1));

        matchedRecepientTextField.setEditable(false);
        matchedRecepientTextField.setText(" ");
        add(matchedRecepientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 488, 118, -1));

        jButton1.setText("Select Donor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, -1, -1));

        jButton2.setText("Select Recepient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        jLabel6.setText("Suitable Match");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 403, -1, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(":");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 488, 26, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
   userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selectedRow = donorListJTable.getSelectedRow();
       if(selectedRow >= 0){
           
             Employee e =   (Employee) donorListJTable.getValueAt(selectedRow, 1);
                    matchedDonorTxtField.setText(e.getName());

       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int selectedRow = recepientListJTable.getSelectedRow();
       if(selectedRow >= 0){
           
             Employee e =   (Employee) recepientListJTable.getValueAt(selectedRow, 1);
                    matchedRecepientTextField.setText(e.getName());
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JTable donorListJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField matchedDonorTxtField;
    private javax.swing.JTextField matchedRecepientTextField;
    private javax.swing.JTable recepientListJTable;
    // End of variables declaration//GEN-END:variables
}
