/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Employee.Donor;
import Business.Employee.Employee;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class CreateDonorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDonorJPanel
     */
    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    public CreateDonorJPanel(JPanel userProcessContainer,OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.directory=directory;
        populateOrgPatientComboBox();
       
        
      
    }
 
     
     
     
    private void populateOrgPatientComboBox() {
         organizationPatientJComboBox.removeAllItems();
        
        for (Organization organization : directory.getOrganizationList()){
            if(organization instanceof DonorOrganization){
              organizationPatientJComboBox.addItem(organization);  
            }
            
        }

    }
 private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) donorJTable.getModel();
        
        model.setRowCount(0);
        for(Organization org : directory.getOrganizationList()){
            if(org instanceof DonorOrganization){
                for (Employee employee : org.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[3];
            row[0] = employee.getId();
            row[1] = employee.getName();
           
            model.addRow(row); 
            }
        }
             
          
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donorJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fNameTxtField = new javax.swing.JTextField();
        organizationPatientJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 164, -1, -1));

        donorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", " Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(donorJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 48, 406, 92));

        addJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addJButton.setText("Create DONOR");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 176, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DONOR Organization :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText(" BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 78, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Donor Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, -1, -1));
        add(fNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 176, -1));

        organizationPatientJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationPatientJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationPatientJComboBoxActionPerformed(evt);
            }
        });
        add(organizationPatientJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 176, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 231, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("View Existing Donors");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Organization organization = (Organization) organizationPatientJComboBox.getSelectedItem();
        String name = fNameTxtField.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter a name","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
            
        else{  
    
        Employee employee=null;
        
        if(organization instanceof DonorOrganization){
            employee=new Donor();
            
        }
        employee.setName(name);
        organization.getEmployeeDirectory().createEmployee(employee);
        //System.out.println("The donor is"+employee);
        JOptionPane.showMessageDialog(null, "The Donor has been created");
        populateTable();
        }
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateTable();    }//GEN-LAST:event_jButton1ActionPerformed

    private void organizationPatientJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationPatientJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationPatientJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable donorJTable;
    private javax.swing.JTextField fNameTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationPatientJComboBox;
    // End of variables declaration//GEN-END:variables

   
}