/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;


import Business.Employee.Donor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorBloodTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class RequestDonorBloodTestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDonorBloodTestsJPanel
     */
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount docAccount;
    private Organization organization;
    private Donor donor;
    public RequestDonorBloodTestsJPanel(JPanel userProcessContainer, UserAccount account,Organization organization, Enterprise enterprise,Donor donor) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.donor=donor;
        this.docAccount=account;
        
        valueLabel.setText(enterprise.getName());
        valueLabel2.setText(donor.getName());
       
         for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
             if(org instanceof LabOrganization){
                 this.organization=(LabOrganization)org;
             }
        }
        populateTable();
    }

      private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) labAsstJTable.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel2 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        msgTxtField = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        labAsstJTable = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueLabel2.setText("<value>");
        add(valueLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 44, 69, -1));

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Donor");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 0, 69, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));

        msgTxtField.setText(" ");
        add(msgTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 196, 193, -1));

        requestTestJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        requestTestJButton.setText("Request Donor Blood Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 237, -1, 31));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 237, 70, 27));

        labAsstJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lab Assistant ID", "Lab Assistant Name"
            }
        ));
        jScrollPane1.setViewportView(labAsstJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 375, 83));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enterpriseLabel1.setText("Message");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        int selectedRow=labAsstJTable.getSelectedRow();

        UserAccount user=null;
        if (selectedRow >= 0) {
            Employee labAsst = (Employee) labAsstJTable.getValueAt(selectedRow, 1);
            DonorBloodTestWorkRequest btwr=new DonorBloodTestWorkRequest();
            for(UserAccount u: organization.getUserAccountDirectory().getUserAccountList())
            {
                if(u.getEmployee()==labAsst)
                {
                    user=u;
                    btwr.setReceiver(u);
                }
            }
            
            
            String msg=msgTxtField.getText();

            //UserAccount nurseUser=getUserAccountForNurse(nurse);
           
            
           
          
               
               btwr.setMessage(msg);
           

            btwr.setSender(docAccount);

            btwr.setRequestDate(new Date());
            btwr.setDonor(donor);

            btwr.setStatus("Initiated");
            user.getWorkQueue().getWorkRequestList().add(btwr);
            //            System.err.println("the nurse is "+user);
            //            System.out.println("the work request is "+nurseUser.getWorkQueue().getWorkRequestList().get(0).getStatus());
  JOptionPane.showMessageDialog(null,"Work Request Created.");
        }
        
        
        else{
            JOptionPane.showMessageDialog(null, "Select a Row");
        }

      

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
       
       
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labAsstJTable;
    private javax.swing.JTextField msgTxtField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel2;
    // End of variables declaration//GEN-END:variables
}
