/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReciepientRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.HormonalRecords.HormonalRecords;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RecordRecepientTempIOTJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordRecepientTempIOTJPanel
     */
     private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HormonalRecords hormonalRecords;
    public RecordRecepientTempIOTJPanel(JPanel userProcessContainer,Enterprise enterprise, Organization organization,  UserAccount userAccount) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        hormonalRecords = new HormonalRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordMyBbtJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tempRecordTxtField = new javax.swing.JTextField();
        backJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordMyBbtJBtn.setText("RECORD MY BBT");
        recordMyBbtJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordMyBbtJBtnActionPerformed(evt);
            }
        });
        add(recordMyBbtJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 30, 130, 57));

        jLabel1.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        jLabel1.setText("Your Basal Body Temperature is:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 517, -1, -1));

        tempRecordTxtField.setEditable(false);
        tempRecordTxtField.setText(" ");
        add(tempRecordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 548, 131, 39));

        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 605, 131, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ReciepientRole/BBTChartTherm.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 115, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void recordMyBbtJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordMyBbtJBtnActionPerformed
         
        
         for( Employee recepient : organization.getEmployeeDirectory().getEmployeeList()){
      if(recepient.getName().equalsIgnoreCase(userAccount.getEmployee().getName())){
          recepient.getHormonalRecordsHistory();
          HormonalRecords hr = recepient.getHormonalRecordsHistory().addHormonalRecords();
          //System.err.println(donor.getHormonalRecordsHistory().getHormonalRecordsList().get(0).gethCGLevels());
             
           double d = hr.generateRecordedTemperature();
      Date date = new Date();
      if(d >= 97.00 && d < 97.4){
          hr.setFollicleStimulatingHormoneLevels(1.5 * d);
          hr.setLeutinizingHormoneLevels(1.75 * d);
          hr.sethCGLevels(0.5 * d +15);
          hr.setRecordedOn(date);
      }
      else if(d >= 97.4 && d < 97.8){
          hr.setFollicleStimulatingHormoneLevels(1.5 * d);
          hr.setLeutinizingHormoneLevels(1.75 * d);
           hr.sethCGLevels(0.5 * d +15);
            hr.setRecordedOn(date);
      }
      
       else if(d >= 97.8 && d < 98.2){
          hr.setFollicleStimulatingHormoneLevels(1.5 * d);
          hr.setLeutinizingHormoneLevels(1.75 * d);
           hr.sethCGLevels(0.5 * d +15);
            hr.setRecordedOn(date);
      }
      
       else if(d >= 98.2 && d < 98.6){
          hr.setFollicleStimulatingHormoneLevels(1.5 * d);
          hr.setLeutinizingHormoneLevels(1.75 * d);
           hr.sethCGLevels(0.5 * d +15);
            hr.setRecordedOn(date);
      }
      
       else if(d >= 98.6 && d < 99.0){
           hr.setFollicleStimulatingHormoneLevels(1.5 * d);
            hr.setLeutinizingHormoneLevels(1.75 * d);
             hr.sethCGLevels(0.5 * d +15);
              hr.setRecordedOn(date);
       }
      
     /* System.out.println("FSH: " +hr.getFollicleStimulatingHormoneLevels());
       System.out.println("LH: " +hr.getLeutinizingHormoneLevels());
       System.out.println("HCG: " +hr.gethCGLevels());
        System.out.println("Date: " +hr.getRecordedOn());*/
        
            tempRecordTxtField.setText(String.valueOf(hr.getTempDropIOT()));
      }
   } 
       
        JOptionPane.showMessageDialog(null, "Your TempDrop record has been taken!");
        
    }//GEN-LAST:event_recordMyBbtJBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
 userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton recordMyBbtJBtn;
    private javax.swing.JTextField tempRecordTxtField;
    // End of variables declaration//GEN-END:variables

}