/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistantRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorBloodTestWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class LabAssistentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistentWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
   private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    public LabAssistentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        
         
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
       this.enterprise = enterprise;
        this.organization =organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        donorTestsJBtn = new javax.swing.JButton();
        recepientTestsJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorTestsJBtn.setText("DONOR TESTS");
        donorTestsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorTestsJBtnActionPerformed(evt);
            }
        });
        add(donorTestsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 151, 93));

        recepientTestsJBtn.setText("RECEPIENT TESTS");
        recepientTestsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepientTestsJBtnActionPerformed(evt);
            }
        });
        add(recepientTestsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 155, 93));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/LabAssistantRole/donor_icon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/LabAssistantRole/recepient_icon.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void donorTestsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorTestsJBtnActionPerformed

        DonorBloodWorkUpsJPanel donorBloodTestWorkRequest = new DonorBloodWorkUpsJPanel(userProcessContainer, organization,enterprise,userAccount);
        userProcessContainer.add("donorBloodTestWorkUp", donorBloodTestWorkRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer); 
    }//GEN-LAST:event_donorTestsJBtnActionPerformed

    private void recepientTestsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepientTestsJBtnActionPerformed
        RecepientBloodWorkUpsJPanel recepientBloodWorkUpsJPanel = new RecepientBloodWorkUpsJPanel(userProcessContainer, organization,enterprise,userAccount);
        userProcessContainer.add("manageOrganizationJPanel", recepientBloodWorkUpsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer); 
    }//GEN-LAST:event_recepientTestsJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorTestsJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton recepientTestsJBtn;
    // End of variables declaration//GEN-END:variables
}
