/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DonorRole;

import Business.Employee.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;

    public DonorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorRecordsJBtn = new javax.swing.JButton();
        tempDropJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorRecordsJBtn.setText("My RECORDS");
        donorRecordsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRecordsJBtnActionPerformed(evt);
            }
        });
        add(donorRecordsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 444, 197, 41));

        tempDropJBtn.setText("TempDrop");
        tempDropJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempDropJBtnActionPerformed(evt);
            }
        });
        add(tempDropJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 503, 197, 38));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jLabel1.setText("Welcome Donor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 18, 197, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DonorRole/egg.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 67, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tempDropJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempDropJBtnActionPerformed
      RecordTempIOTJPanel recordTempIOTJPanel= new RecordTempIOTJPanel(userProcessContainer, enterprise,organization,userAccount);
        userProcessContainer.add("createDonorJPanel", recordTempIOTJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_tempDropJBtnActionPerformed

    private void donorRecordsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRecordsJBtnActionPerformed
 DonorRecordsJPanel donorRecordsJPanel = new DonorRecordsJPanel(userProcessContainer, enterprise,organization,userAccount);
        userProcessContainer.add("createDonorJPanel", donorRecordsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);      }//GEN-LAST:event_donorRecordsJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorRecordsJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tempDropJBtn;
    // End of variables declaration//GEN-END:variables
}
