/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorPoolJBtn = new javax.swing.JButton();
        recepientPoolJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorPoolJBtn.setText("DONOR POOL");
        donorPoolJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorPoolJBtnActionPerformed(evt);
            }
        });
        add(donorPoolJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 229, 146, 47));

        recepientPoolJBtn.setText("RECEPIENT POOL");
        recepientPoolJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepientPoolJBtnActionPerformed(evt);
            }
        });
        add(recepientPoolJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 228, 146, 49));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/recepient_icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 61, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/donor_icon.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 61, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void donorPoolJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorPoolJBtnActionPerformed
     ManageDonorJPanel manageDonorJPanel = new ManageDonorJPanel(userProcessContainer, enterprise,organization,userAccount);
        userProcessContainer.add("createDonorJPanel", manageDonorJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    }//GEN-LAST:event_donorPoolJBtnActionPerformed

    private void recepientPoolJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepientPoolJBtnActionPerformed
ManageRecepientJPanel manageRecepientJPanel = new ManageRecepientJPanel(userProcessContainer, enterprise,organization,userAccount);
        userProcessContainer.add("createDonorJPanel", manageRecepientJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);      }//GEN-LAST:event_recepientPoolJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorPoolJBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton recepientPoolJBtn;
    // End of variables declaration//GEN-END:variables
}
