/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Employee.Employee;
import Business.Employee.Recepient;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.ReciepientOrganization;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageRecepientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRecepientJPanel
     */
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    public ManageRecepientJPanel(JPanel userProcessContainer,Enterprise enterprise,Organization organization,UserAccount userAccount) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.organization=organization;
        
        valueLabel.setText(enterprise.getName());
         
         populateTable();
         
    }
    
     private void populateTable() {
      DefaultTableModel model = (DefaultTableModel) donorJTable.getModel();
        
        model.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof ReciepientOrganization){
                 for (Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[3];
            row[0] = emp.getId();
            row[1] = emp;
            
            model.addRow(row);
        }   
                
            }
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        physicalTestsJBtn = new javax.swing.JButton();
        bloodTestsJBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        donorJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        viewTestResultsJBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 16, 158, 26));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 127, 30));

        physicalTestsJBtn.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        physicalTestsJBtn.setText("PHYSICAL TESTS");
        physicalTestsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalTestsJBtnActionPerformed(evt);
            }
        });
        add(physicalTestsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 167, 50));

        bloodTestsJBtn.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        bloodTestsJBtn.setText("BLOOD TESTS");
        bloodTestsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTestsJBtnActionPerformed(evt);
            }
        });
        add(bloodTestsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 167, 52));

        donorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Recepient ID", "Recepient  Name"
            }
        ));
        jScrollPane2.setViewportView(donorJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 444, 87));

        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 78, 33));

        viewTestResultsJBtn.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        viewTestResultsJBtn.setText("VIEW TEST RESULTS");
        viewTestResultsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTestResultsJBtnActionPerformed(evt);
            }
        });
        add(viewTestResultsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 170, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void physicalTestsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalTestsJBtnActionPerformed
        int selectedRow=donorJTable.getSelectedRow();

        

      if (selectedRow >= 0) {
            Employee recepient = (Employee) donorJTable.getValueAt(selectedRow, 1);

          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestRecepientPhysicalTestsJPanel", new RequestRecepientPhysicalTestsJPanel(userProcessContainer, userAccount, organization, enterprise,recepient));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_physicalTestsJBtnActionPerformed

    private void bloodTestsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTestsJBtnActionPerformed
 int selectedRow=donorJTable.getSelectedRow();
      Organization organization = new LabOrganization();
      if (selectedRow >= 0) {
            Recepient recepient = (Recepient) donorJTable.getValueAt(selectedRow, 1);

          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestDonorBloodTests", new RequestRecepientBloodTestsJPanel(userProcessContainer, userAccount, organization, enterprise,recepient));
            layout.next(userProcessContainer);
        } 
    }//GEN-LAST:event_bloodTestsJBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewTestResultsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTestResultsJBtnActionPerformed
int selectedRow=donorJTable.getSelectedRow();

      if (selectedRow >= 0) {
            Employee recepient = (Employee) donorJTable.getValueAt(selectedRow, 1);

          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ViewTestResults", new ViewRecepientTestResultsJPanel(userProcessContainer, enterprise,userAccount, organization ,recepient));
            layout.next(userProcessContainer);
      }
    }//GEN-LAST:event_viewTestResultsJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton bloodTestsJBtn;
    private javax.swing.JTable donorJTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton physicalTestsJBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewTestResultsJBtn;
    // End of variables declaration//GEN-END:variables
}
