/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public NurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
           
         this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise=enterprise;
        this.organization =organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recepientTestsJBtn1 = new javax.swing.JButton();
        donorTestsJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recepientTestsJBtn1.setText("RECEPIENT TESTS");
        recepientTestsJBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepientTestsJBtn1ActionPerformed(evt);
            }
        });
        add(recepientTestsJBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 146, 93));

        donorTestsJBtn.setText("DONOR TESTS");
        donorTestsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorTestsJBtnActionPerformed(evt);
            }
        });
        add(donorTestsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 141, 93));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/NurseRole/donor_icon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/NurseRole/recepient_icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void recepientTestsJBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepientTestsJBtn1ActionPerformed
      RecepientPhyWorkUpJPanel recepientPhyWorkUpJPanel = new RecepientPhyWorkUpJPanel(userProcessContainer, organization,enterprise,userAccount);
        userProcessContainer.add("donorPhyWorkUp", recepientPhyWorkUpJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_recepientTestsJBtn1ActionPerformed

    private void donorTestsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorTestsJBtnActionPerformed
 DonorPhyWorkUpJPanel donorPhyWorkUpJPanel = new DonorPhyWorkUpJPanel(userProcessContainer, organization,enterprise,userAccount);
        userProcessContainer.add("donorPhyWorkUp", donorPhyWorkUpJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
     }//GEN-LAST:event_donorTestsJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorTestsJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton recepientTestsJBtn1;
    // End of variables declaration//GEN-END:variables
}
